### ISSUE TITLE
Clarify and understand what is in frames.bin test; make this less confusing or error-prone

### ISSUE THREAD

**Issue by roland-sipos** [DUNE-DAQ/readoutlibs#11]

**Comment by roland-sipos** [comment]
Discussion needed on asset management.

**Comment by jmcarcell** [comment]
I tried to find the parent file by doing a search over all the binary files in the protodune folder in eos and none of those was the parent.

**Comment by plasorak** [comment]
Any news on that @alessandrothea ? This has some importance for k8s (frames.bin is downloaded in the image) and in flxlibs (one needs to generate the emulator patterns everytime)... It'd be good to have at least a direction on how to fix this.

**Comment by roland-sipos** [comment]
Closing issue thanks to "assets management" tool.
