### ISSUE TITLE
Make a request handler model suitable for use with trigger objects

### ISSUE THREAD

**Issue by philiprodrigues** [DUNE-DAQ/readoutlibs#15]
We'd like to re-use the readoutlibs latency buffer and request handling code for the trigger objects (TPs, TAs, TCs) in order to have consistent behaviour between readout and trigger. Here's a rough proposal. There's work towards this proposal on the `philiprodrigues/readoutlibs-buffer` branch of `trigger`:

We use [DefaultRequestHandlerModel](https://github.com/DUNE-DAQ/readoutlibs/blob/develop/include/readoutlibs/models/DefaultRequestHandlerModel.hpp) mostly unchanged, and DS provides an implementation of a `ReadoutType` in the style of the ones in [FDReadoutTypes](https://github.com/DUNE-DAQ/fdreadoutlibs/blob/develop/include/fdreadoutlibs/FDReadoutTypes.hpp). The `ReadoutType` is geared towards the structure of a FELIX superchunk, where the object that's buffered consists of multiple smaller frames, with different timestamps. We can shoehorn the trigger objects into this format by saying they just consist of a single frame, and `DefaultRequestHandlerModel` should do the right thing. We do that with a "wrapper" object in `trigger` that holds the trigger object itself, and provides the functions/members required by `ReadoutType`. In the long term, it would be nice to have a `ReadoutType` structure that's a closer fit to the structure of the trigger objects, but we can get something working with what we have now.

There's one place where the `ReadoutType` structure _does_ need to be changed, which is that it requires the "underlying" type (eg, the `TriggerPrimitive` itself, rather than the wrapper object) to have a `get_timestamp()` function. This doesn't make sense for trigger objects, which have multiple timestamps associated. The line that leads to this requirement is:

https://github.com/DUNE-DAQ/readoutlibs/blob/aed80be4525e7e01b11b1f45b118811b5f1a8abf/include/readoutlibs/models/DefaultRequestHandlerModel.hpp#L565

I'm not actually sure of how to fix this. Add a `get_iter_timestamp(iterator)` member function in each implementation of `ReadoutType`? or perhaps a free function, in the style of `operator<<` for iostreams?

**Comment by roland-sipos** [comment]
@philiprodrigues is the linked PR resolves this?

**Comment by philiprodrigues** [comment]
Yes. Closed by #16
