### ISSUE TITLE
Empty fragments from `DefaultRequestHandlerModel` on low-rate inputs

### ISSUE THREAD

**Issue by philiprodrigues** [DUNE-DAQ/readoutlibs#17]
When `DefaultRequestHandlerModel` gets a request for data in a time window `[start, end]`, it waits until the latency buffer has an object with time > `end`, so that it knows it has all of the data in the window (assuming the inputs are time-ordered). If an object with time > `end` does not arrive within the timeout period, the request times out and an empty fragment is returned.

This situation is very unlikely with high-rate inputs, such as WIB frames, but is much more likely with downstream objects from the DS system, such as Trigger candidates.

I think the easiest and most general way of dealing with this is to have `DefaultRequestHandlerModel` return a "partial" fragment at timeout, with whatever is in the buffer. We'll have to make sure there is some way to indicate that the fragment _may_ be incomplete (a flag in `FragmentHeader`, presumably).

Another possible approach is to have the code that feeds the buffer add periodic "fake" TCs so that the request handler will see a (fake) object with time > `end`, even if a real TC has not yet arrived. The disadvantages I see to this approach are that it requires the feeder code to know that clock rate, so it doesn't get too far ahead, and requires the feeder code to handle the case where it's fed a fake TC with time `t` and then receives a _real_ TC with time < `t`.

**Comment by jimbrooke** [comment]
I changed the WG tag from Readout to CoreSW

**Comment by roland-sipos** [comment]
I'm very much against to "fake" data in this context. Manipulating incoming data in the rawprocessor is expected/allowed, but fabricating extra payloads within seems very weird to me. 

I agree with you that the most general way of dealing with this would be to still respond with partial, not fully closed time windows on timed-out requests. I'll look into this fix.

**Comment by roland-sipos** [comment]
Apparently we already have a reserved error bit in the fragment header for this:
https://github.com/DUNE-DAQ/daqdataformats/blob/db0f11981bea89c0ec56e8a4077fe930feff9f32/include/daqdataformats/FragmentHeader.hpp#L139

**Comment by philiprodrigues** [comment]
I made a start on an attempt to do the responding with partial fragments. I will try to push the branch today for you to have a look at
