### ISSUE TITLE
Record on NFS storage for ZeroCopyRecordingRequestHandlerModel

### ISSUE THREAD

**Issue by plasorak** [DUNE-DAQ/readoutlibs#45]
The record command for ZeroCopyRecordingRequestHandlerModel doesn't work when the output file is meant to be on an NFS storage. Roland says this is because a file descriptor flag (O_DIRECT) is set, and it doesn't work on NFS.

**Comment by roland-sipos** [comment]
This is expected. The ZeroCopyRecording is designed for the SNB capture, hence the reason it will work only with specific storage volume attached to the RU.

**Comment by plasorak** [comment]
Won't fix
